### ISSUE TITLE
Nested template names contain backslashes when compiled on Windows

### ISSUE THREAD

**Issue by jneurock** [Geodesigner/gulp-ember-template-compiler#2]
When compiling templates on Windows, nested template names contain backslashes and it appears Ember can't resolve these. For example, a component template named `nav-item` might be found in `hbs\components\nav-item.hbs` on Windows. The plugin assigns this template to `Ember.TEMPLATES['components\nav-item']` but it appears Ember expects `Ember.TEMPLATES['components/nav-item']`.

Could a fix for this be as simple as changing line 24 in `index.js` as follows?
`file.contents = new Buffer("Ember.TEMPLATES['" + fileName.replace(/\\/g, '/') +"'] = Ember.Handlebars.template(" + compilerOutput + ");");`

**Comment by acburdine** [comment]
I created a PR that should fix this.

**Comment by Gaudj** [comment]
Get it, Thanks!
